# -*- coding: utf-8 -*-
"""лаба№1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15XKmx7Cv0hGCLQPc_uJvsrQFNfeztGNu
"""

print("Hello World")

a = 5
b = int(input())
c = a*b
print (c)

a = int(input())
b = int(input())
c = (a+b)**2
print (c)

a = 15
b = 10
c = int(input())
d = (a+b)/c 
print (d)

a = int(input())
b = int(input())
c = (a+b)**2
print (c)

a = 4
b = 3
c = 5
p = (a+b+c)
print (p)

a = 5
b = 4
c = ((a**3+14)/5)*b
print (c)

a = 7
b = (a**2)//2
print (b)

a = int(input())
b = int(input())
d = int(input())
e = int(input())
c = (a/b)//(d/e)
print (c)

a = int(input())
b = int(input())
c = a*b
print (c)

a = int(input())
b = int(input())
c = a/b
print (c)

s = 120000
m = s/60
print (m)
h = m/60
print (h)
d = h/24
print (d)

n = 5
a = (n+n**2+n**3)
print (a)